---
- sysctl:
    name: net.core.somaxconn
    value: '32768'
    state: present

- sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: '1'
    state: present

- sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: '10'
    state: present

- sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: '2000000'
    state: present

- sysctl:
    name: net.core.netdev_max_backlog
    value: '8192'
    state: present

